# Catppuccin Mocha - Kitty Theme
foreground              #cdd6f4
background              #1e1e2e
selection_foreground    #1e1e2e
selection_background    #f5e0dc

# Cursor colors
cursor                  #f5e0dc
cursor_text_color       #1e1e2e

# URL underline color when hovering with mouse
url_color               #f5e0dc
url_style               curly

# Kitty window border colors
active_border_color     #b4befe
inactive_border_color   #6c7086
bell_border_color       #f9e2af

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #11111b
active_tab_background   #cba6f7
inactive_tab_foreground #cdd6f4
inactive_tab_background #181825
tab_bar_background      #11111b

# Colors for marks (marked text in the terminal)
mark1_foreground #1e1e2e
mark1_background #b4befe
mark2_foreground #1e1e2e
mark2_background #cba6f7
mark3_foreground #1e1e2e
mark3_background #74c7ec

# The 16 terminal colors

# black (Tông tối làm nền phụ)
color0 #313244
color8 #45475a

# red (Thay vì đỏ rực, đổi sang Đỏ sẫm pha xanh / Mận chín hoặc Xanh đậm nếu muốn bỏ hẳn màu đỏ)
# Gợi ý: Dùng màu Burgundy/Rosewater sẫm để giữ tính năng cảnh báo (Error) nhưng không bị chói.
color1 #e64553
color9 #f38ba8

# green (Xanh biển sáng / Xanh Mint dịu)
color2  #74c7ec
color10 #89b4fa

# yellow (Đổi từ vàng chói sang màu Cát/Vàng đất nhạt hoặc Xanh rêu biển để hợp tone dark blue)
color3  #b4befe
color11 #cdd6f4

# blue (Xanh biển đậm chính - Royal Blue / Sapphire)
color4  #1e66f5
color12 #74c7ec

# magenta (Đổi từ hồng phấn sang Tím than / Tím Lavender đậm)
color5  #7287fd
color13 #b4befe

# cyan (Đổi từ màu xanh ngọc chói sang Xanh băng / Xanh xám nhạt Teal dịu mắt)
color6  #209fb5
color14 #94e2d5

# white (Trắng xám dịu)
color7  #bac2de
color15 #cdd6f4
