foreground         #FFF7F5
background         #181A1E
cursor             #F4A1C4

active_tab_foreground     #181A1E
active_tab_background     #B0386F
inactive_tab_foreground   #FFF7F5
inactive_tab_background   #181A1E

active_border_color   #4C586E
inactive_border_color #181A1E
bell_border_color     #B58A95

color0      #2C2E33
color8      #ACA5A2
color1      #4C586E
color9      #667592
color2      #B0386F
color10     #EA4A94
color3      #B58A95
color11     #F1B8C7
color4      #919FB2
color12     #C1D4ED
color5      #BEAFA9
color13     #FEE9E1
color6      #BEAFA9
color14     #FEE9E1
color7      #F6ECE8
color15     #F6ECE8
