enc_id = '00AYDIRlXjookLAXc2s6QigG6nXeDBMmkwT6PZSNynRCuEab0YNPJbgZcKmNefx6lqjw=='
password = '01ARd+N5dKH/FhenbJRTaTUXWLtnybyOdAQTcOtUoqBQI4Xj100+/3/yxpl8P5RQ2cNVuimWlVoFVbd6fWFJJJtXUTRGs3p448/jTzWJRH1df6NFlmkL+1'
salt = 'wj2ce69fkm3ij52ynbd9wfrutqpw6pfj'
key_pair = [
    [
    154,
    123,
    175,
    105,
    142,
    186,
    114,
    233,
    159,
    202,
    182,
    210,
    124,
    177,
    120,
    92,
    19,
    41,
    239,
    66,
    206,
    58,
    228,
    52,
    120,
    61,
    217,
    19,
    59,
    25,
    167,
    35,
    47,
    129,
    233,
    253,
    113,
    64,
    78,
    120,
    252,
    134,
    62,
    28,
    91,
    13,
    186,
    28,
    105,
    149,
    238,
    226,
    201,
    32,
    181,
    203,
    57,
    169,
    214,
    47,
    236,
    235,
    115,
    157,
],
    [
    47,
    129,
    233,
    253,
    113,
    64,
    78,
    120,
    252,
    134,
    62,
    28,
    91,
    13,
    186,
    28,
    105,
    149,
    238,
    226,
    201,
    32,
    181,
    203,
    57,
    169,
    214,
    47,
    236,
    235,
    115,
    157,
],
]
key_confirmed = true

[keys_confirmed]
rs-ny = true
