rendezvous_server = 'rs-ny.rustdesk.com:21116'
nat_type = 1
serial = 0
unlock_pin = ''
trusted_devices = '00ASq1XYyy5CS7OIE2cfFucXXCHuZ2R3A0EeatngktQ8EL0dDyvbmD/WvqyQ=='

[options]
av1-test = 'Y'
verification-method = 'use-permanent-password'
local-ip-addr = '192.168.101.66'
