enc_id = '00AYDIRlXjookLAXc2s6QigG6nXeDBMmkwT6PZSNynRCuEab0YNPJbgZcKmNefx6lqjw=='
password = '01ARd+N5dKH/FhenbJRTaTUXWLtnybyOdAQTcOtUoqBQI4Xj100+/3/yxpl8P5RQ2cNVuimWlVoFVbd6fWFJJJtXUTRGs3p448/jTzWJRH1df6NFlmkL+1'
salt = 'wj2ce69fkm3ij52ynbd9wfrutqpw6pfj'
key_pair = [
    [
    222,
    160,
    253,
    135,
    231,
    115,
    18,
    107,
    17,
    54,
    92,
    23,
    105,
    14,
    223,
    154,
    208,
    79,
    63,
    147,
    248,
    64,
    190,
    95,
    190,
    199,
    27,
    117,
    186,
    124,
    149,
    30,
    37,
    212,
    210,
    4,
    198,
    89,
    175,
    86,
    39,
    73,
    83,
    18,
    159,
    32,
    107,
    243,
    141,
    129,
    42,
    161,
    84,
    176,
    225,
    181,
    182,
    90,
    171,
    111,
    175,
    44,
    84,
    86,
],
    [
    37,
    212,
    210,
    4,
    198,
    89,
    175,
    86,
    39,
    73,
    83,
    18,
    159,
    32,
    107,
    243,
    141,
    129,
    42,
    161,
    84,
    176,
    225,
    181,
    182,
    90,
    171,
    111,
    175,
    44,
    84,
    86,
],
]
key_confirmed = true

[keys_confirmed]
rs-ny = true
