remote_id = ''
kb_layout_type = ''
size = [
    0,
    0,
    0,
    0,
]
fav = []

[options]
access_token = 'gxQvQGoKS/W7b902U2YuXQ=='
user_info = '{"name":"tiến nguyễn-google-1","display_name":"","avatar":"","status":1}'

[ui_flutter]
wm_Main = '{"width":null,"height":null,"offsetWidth":null,"offsetHeight":null,"isMaximized":true,"isFullscreen":false}'
peer-sorting = 'Remote ID'
