backend = "fastresize"
color_space = "labmixed"
palette = "dark16"

[templates]
hyprland = { template = 'hyprland.conf.tera', target = '~/.config/hypr/wallust-colors.conf' }
kitty = { template = 'kitty.conf.tera', target = '~/.config/kitty/wallust-colors.conf' }
waybar = { template = 'waybar.css.tera', target = '~/.config/waybar/wallust-colors.css' }
rofi = { template = 'rofi.rasi.tera', target = '~/.config/rofi/wallust-colors.rasi' }
swaync = { template = 'swaync.css.tera', target = '~/.config/swaync/wallust-colors.css' }

