general {
    lock_cmd = pidof hyprlock || hyprlock       # Lệnh gọi màn hình khóa
    before_sleep_cmd = loginctl lock-session    # Đảm bảo máy tự khóa trước khi rơi vào trạng thái Suspend
    after_sleep_cmd = hyprctl dispatch "hl.dsp.dpms('on')"  # Bật lại tín hiệu màn hình khi máy thức dậy
}

# 1. Sau 5 phút (300s): Giảm độ sáng màn hình
listener {
    timeout = 300
    on-timeout = brightnessctl -s set 5%       # Lưu độ sáng hiện tại và giảm xuống 5%
    on-resume = brightnessctl -r                # Khôi phục lại độ sáng cũ khi lắc chuột
}

# 2. Sau 6 phút (360s): Tắt hẳn tín hiệu màn hình (Máy vẫn chạy)
listener {
    timeout = 360
    on-timeout = hyprctl dispatch "hl.dsp.dpms('off')"
    on-resume = hyprctl dispatch "hl.dsp.dpms('on')"
}

# 3. Sau 10 phút (600s): Khóa màn hình
listener {
    timeout = 600
    on-timeout = loginctl lock-session
}

# 4. Sau 15 phút: Đưa máy vào trạng thái Suspend (Giống Sleep trên Windows)
listener {
    timeout = 900
    on-timeout = systemctl suspend
}
