-- Generated by nwg-displays on 2026-06-29 at 10:54:30. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@60.209999999999994",
    position = "0x0",
    scale = 1.0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@60.0",
    position = "1920x0",
    scale = 1.0
})
