-- Generated by nwg-displays on 2026-07-07 at 02:56:14. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@60.0",
    position = "0x0",
    scale = 1.0
})
hl.monitor({
    output = "HDMI-A-1",
    disabled = true
})
