$background = rgb(181A1E)
$foreground = rgb(FFF7F5)
$color0 = rgb(2C2E33)
$color1 = rgb(4C586E)
$color2 = rgb(B0386F)
$color3 = rgb(B58A95)
$color4 = rgb(919FB2)
$color5 = rgb(BEAFA9)
$color6 = rgb(BEAFA9)
$color7 = rgb(F6ECE8)
$color8 = rgb(ACA5A2)
$color9 = rgb(667592)
$color10 = rgb(EA4A94)
$color11 = rgb(F1B8C7)
$color12 = rgb(C1D4ED)
$color13 = rgb(FEE9E1)
$color14 = rgb(FEE9E1)
$color15 = rgb(F6ECE8)
